version: '3.2'
services:
  rabbitmq_bootcamp:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq_bootcamp
    networks:
      - backend
  postgres_bootcamp:
    build:
      context: ./postgres
    image: aleaguiarl/postgres_bootcamp:latest
    ports:
      - 5432:5432
    container_name: postgres_bootcamp
    networks:
      - backend
  bootcamp-user-api:
    build:
      context: ../alexandre-aguiar-backend/app-user-api
      dockerfile: ../app-user-api/Dockerfile
    image: aleaguiarl/app-user-api:latest
    ports:
      - 8081:8081
    container_name: app-user-api
    environment:
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
      - RABBITMQ_HOST=rabbitmq_bootcamp
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - postgres_bootcamp
      - rabbitmq_bootcamp
    networks:
      - backend
  bootcamp-integration-api:
    build:
      context: ../alexandre-aguiar-backend/app-integration-api
      dockerfile: ../app-integration-api/Dockerfile
    image: aleaguiarl/app-integration-api:latest
    ports:
      - 8082:8082
    container_name: app-integration-api
    environment:
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
      - RABBITMQ_HOST=rabbitmq_bootcamp
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - postgres_bootcamp
      - rabbitmq_bootcamp
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
